KEY_FILE = "service_account.json"
SHEET_IDENTIFIER = "1qV0kUm-jko3CyIe1EeU8BC7XsBEuSCHWUsK5wQrEylg"
VOCAB_TAB_NAME = "Vokabeln"
PERFORMANCE_TAB_NAME = "Performance"
SOURCE_LANG = "fr"
TRANSLATION_LANG = "de"
CATEGORY_COL = "category"
